### ISSUE TITLE
BraintreeHttp\\HttpException (code: 0) When I call OrdersGetRequest

### ISSUE THREAD

**Issue by JellyBool** [paypal/Checkout-PHP-SDK#33]
### Error log:

```
[2019-10-24 16:13:52] local.ERROR:  {"exception":"[object] (BraintreeHttp\\HttpException(code: 0):  at /Users/jellybool/sites/parking/vendor/braintree/braintreehttp/lib/BraintreeHttp/HttpClient.php:185)
[stacktrace]
#0 /Users/jellybool/sites/parking/vendor/braintree/braintreehttp/lib/BraintreeHttp/HttpClient.php(97): BraintreeHttp\\HttpClient->parseResponse(Object(BraintreeHttp\\Curl))
#1 /Users/jellybool/sites/parking/app/Http/Controllers/PaypalController.php(13): BraintreeHttp\\HttpClient->execute(Object(PayPalCheckoutSdk\\Orders\\OrdersGetRequest))
#2 [internal function]: App\\Http\\Controllers\\PaypalController->checkout()
#3 /Users/jellybool/sites/parking/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#4 /Users/jellybool/sites/parking/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('checkout', Array)
#5 /Users/jellybool/sites/parking/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\PaypalController), 'checkout')
#6 /Users/jellybool/sites/parking/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#7 /Users/jellybool/sites/parking/vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\\Routing\\Route->run()
#8 /Users/jellybool/sites/parking/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#9 /Users/jellybool/sites/parking/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#10 /Users/jellybool/sites/parking/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#11 /Users/jellybool/sites/parking/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#12 /Users/jellybool/sites/parking/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle(Object(Illuminate\\Http\\Request), Object(Closure), 60, '1')
#13 /Users/jellybool/sites/parking/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#14 /Users/jellybool/sites/parking/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#15 /Users/jellybool/sites/parking/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#16 /Users/jellybool/sites/parking/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#17 /Users/jellybool/sites/parking/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#18 /Users/jellybool/sites/parking/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#19 /Users/jellybool/sites/parking/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#20 /Users/jellybool/sites/parking/nova/src/Http/Middleware/ServeNova.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /Users/jellybool/sites/parking/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Laravel\\Nova\\Http\\Middleware\\ServeNova->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 /Users/jellybool/sites/parking/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /Users/jellybool/sites/parking/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /Users/jellybool/sites/parking/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /Users/jellybool/sites/parking/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /Users/jellybool/sites/parking/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /Users/jellybool/sites/parking/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /Users/jellybool/sites/parking/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /Users/jellybool/sites/parking/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /Users/jellybool/sites/parking/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /Users/jellybool/sites/parking/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /Users/jellybool/sites/parking/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /Users/jellybool/sites/parking/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#34 /Users/jellybool/sites/parking/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#35 /Users/jellybool/sites/parking/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#36 /Users/jellybool/.composer/vendor/laravel/valet/server.php(158): require('/Users/jellyboo...')
#37 {main}
"} 
```

### Server-side PHP :

`PayPalClient.php`

```php
use PayPalCheckoutSdk\Core\PayPalHttpClient;
use PayPalCheckoutSdk\Core\SandboxEnvironment;
use PayPalCheckoutSdk\Core\ProductionEnvironment;

/**
 * Class PayPalClient
 * @package App\Services
 */
class PayPalClient {
    /**
     * @return PayPalHttpClient
     */
    public static function client()
    {
        return new PayPalHttpClient(self::environment());
    }

    /**
     * Set up and return PayPal PHP SDK environment with PayPal access credentials.
     * This sample uses SandboxEnvironment. In production, use LiveEnvironment.
     */
    public static function environment()
    {
        if (app()->environment() === 'production') {
            return new ProductionEnvironment(config('services.paypal.id'), config('services.paypal.secret'));
        }
        return new SandboxEnvironment(config('services.paypal.id'), config('services.paypal.secret'));
    }
}
```
`PaypalController.php`:
```php
use App\Services\PayPalClient;
use PayPalCheckoutSdk\Orders\OrdersGetRequest;

class PaypalController extends Controller {
     public function executeOrder()
    {
        $client = PayPalClient::client();
        // Error 
        $response = $client->execute(new OrdersGetRequest(request('orderId')));

        return $response->result->status; 
    }
}
```

### Client-side:

```html
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row mb-4">
            <div class="col-md-10">
                <div id="paypal-button-container"></div>
            </div>
        </div>
    </div>

@endsection

@section('js')
    <script src="https://www.paypal.com/sdk/js?client-id=AbiYsKz9BiwLqoX69NOgeZ7GElaRSIM9JWVOcC1KpXoo_kAe3vYo8t8Lwm0k6nEdvHRg7KLpb7fKnCCQ"></script>

    <script>
        window.onload = function () {
            paypal.Buttons({
                style: {
                    layout:  'vertical',
                    color:   'blue',
                    shape:   'rect',
                    label:   'pay'
                },
                createOrder: function (data, actions) {
                    return actions.order.create({
                        purchase_units: [{
                            amount: {
                                currency_code: 'USD',
                                value: '2.00'
                            }
                        }]
                    });
                },
                onApprove: function (data, actions) {
                    return actions.order.capture().then(function (details) {
                        console.log(data);
                        console.log(details);
                        // Hit server code executeOrder() 
                        return axios.post('/api/paypal/execute', {orderId: data.orderID});
                    });
                }
            }).render('#paypal-button-container');
        }
    </script>

@endsection
```

Similar to https://github.com/paypal/Checkout-PHP-SDK/issues/31 

But I can't figure it out. Any idea what's going on?

**Comment by tiffanyrzhou** [comment]
@JellyBool We will look into this issue. Thanks for reaching out!

**Comment by tiffanyrzhou** [comment]
@JellyBool  Can you share the base url for the Production Environment you are using? It should be located in the file PayPalCheckoutSdk\Core\ProductionEnvironment.php.

**Comment by JellyBool** [comment]
Sorry, I haven't push it to production！ It happened on Sanbox Environment when I interacted Paypal in my local development.

**Comment by tiffanyrzhou** [comment]
Okay! Can we confirm the sandbox base url we're looking at is https://api.sandbox.paypal.com. 
Additionally, can you provide the order id from the request that returned an error? Thanks!

**Comment by JellyBool** [comment]
@tiffanyrzhou `orderID: 53J812981B004423B`

**Comment by tiffanyrzhou** [comment]
@JellyBool Can you print the status code from Braintree/HTTPClient for me from the parseResponse method? The file should be located under vendor/braintree/braintreehttp/lib/BraintreeHttp. Thanks!

**Comment by JellyBool** [comment]
I got it working, turns out my fault. It should be :

```php
 $response = $client->execute(new OrdersGetRequest(request('orderID'))); // Not request('orderId')
```

So sorry for this. @tiffanyrzhou
